export enum OBJECTS {
    NONE = 'NONE',
    VERTICAL = 'VERTICAL',
    HORIZONTAL = 'HORIZONTAL',
    LEFTDOWN = 'LEFTDOWN',
    LEFTUP = 'LEFTUP',
    RIGHTDOWN = 'RIGHTDOWN',
    RIGHTUP = 'RIGHTUP'
}

export enum DIRECTIONS {
    UP = 'UP',
    DOWN = 'DOWN',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT'
}

export type MAP = OBJECTS[][]

type RULES = {
    [key in OBJECTS]?: { [key in DIRECTIONS]?: OBJECTS[] }
}
export const allowed_objects_rules: RULES = {
    [OBJECTS.HORIZONTAL]: {
        [DIRECTIONS.RIGHT]: [OBJECTS.LEFTDOWN, OBJECTS.HORIZONTAL],
        [DIRECTIONS.LEFT]: [OBJECTS.RIGHTDOWN, OBJECTS.RIGHTUP, OBJECTS.HORIZONTAL]
    },
    [OBJECTS.VERTICAL]: {
        [DIRECTIONS.UP]: [OBJECTS.LEFTDOWN, OBJECTS.RIGHTDOWN, OBJECTS.VERTICAL],
        [DIRECTIONS.DOWN]: [OBJECTS.RIGHTUP, OBJECTS.VERTICAL]
    },
    [OBJECTS.LEFTDOWN]: {
        [DIRECTIONS.DOWN]: [OBJECTS.RIGHTUP, OBJECTS.VERTICAL],
        [DIRECTIONS.LEFT]: [OBJECTS.RIGHTUP, OBJECTS.RIGHTDOWN, OBJECTS.HORIZONTAL],
    },
    [OBJECTS.LEFTUP]: {
        [DIRECTIONS.UP]: [OBJECTS.RIGHTDOWN, OBJECTS.LEFTDOWN, OBJECTS.VERTICAL],
        [DIRECTIONS.LEFT]: [OBJECTS.RIGHTDOWN, OBJECTS.RIGHTUP, OBJECTS.HORIZONTAL],
    },
    [OBJECTS.RIGHTDOWN]: {
        [DIRECTIONS.DOWN]: [OBJECTS.RIGHTUP, OBJECTS.VERTICAL],
        [DIRECTIONS.RIGHT]: [OBJECTS.LEFTDOWN, OBJECTS.HORIZONTAL],
    },
    [OBJECTS.RIGHTUP]: {
        [DIRECTIONS.UP]: [OBJECTS.LEFTDOWN, OBJECTS.RIGHTDOWN, OBJECTS.VERTICAL],
        [DIRECTIONS.RIGHT]: [OBJECTS.LEFTDOWN, OBJECTS.HORIZONTAL],
    },
}
// export const allowed_objects_rules: RULES = {
//     [OBJECTS.HORIZONTAL]: {
//         [DIRECTIONS.RIGHT]: [OBJECTS.LEFTDOWN, OBJECTS.LEFTUP, OBJECTS.HORIZONTAL],
//         [DIRECTIONS.LEFT]: [OBJECTS.RIGHTDOWN, OBJECTS.RIGHTUP, OBJECTS.HORIZONTAL]
//     },
//     [OBJECTS.VERTICAL]: {
//         [DIRECTIONS.UP]: [OBJECTS.LEFTDOWN, OBJECTS.RIGHTDOWN, OBJECTS.VERTICAL],
//         [DIRECTIONS.DOWN]: [OBJECTS.LEFTUP, OBJECTS.RIGHTUP, OBJECTS.VERTICAL]
//     },
//     [OBJECTS.LEFTDOWN]: {
//         [DIRECTIONS.DOWN]: [OBJECTS.LEFTUP, OBJECTS.RIGHTUP, OBJECTS.VERTICAL],
//         [DIRECTIONS.LEFT]: [OBJECTS.RIGHTUP, OBJECTS.RIGHTDOWN, OBJECTS.HORIZONTAL],
//     },
//     [OBJECTS.LEFTUP]: {
//         [DIRECTIONS.UP]: [OBJECTS.RIGHTDOWN, OBJECTS.LEFTDOWN, OBJECTS.VERTICAL],
//         [DIRECTIONS.LEFT]: [OBJECTS.RIGHTDOWN, OBJECTS.RIGHTUP, OBJECTS.HORIZONTAL],
//     },
//     [OBJECTS.RIGHTDOWN]: {
//         [DIRECTIONS.DOWN]: [OBJECTS.LEFTUP, OBJECTS.RIGHTUP, OBJECTS.VERTICAL],
//         [DIRECTIONS.RIGHT]: [OBJECTS.LEFTUP, OBJECTS.LEFTDOWN, OBJECTS.HORIZONTAL],
//     },
//     [OBJECTS.RIGHTUP]: {
//         [DIRECTIONS.UP]: [OBJECTS.LEFTDOWN, OBJECTS.RIGHTDOWN, OBJECTS.VERTICAL],
//         [DIRECTIONS.RIGHT]: [OBJECTS.LEFTDOWN, OBJECTS.LEFTUP, OBJECTS.HORIZONTAL],
//     },
// }

type DIRECTIONS_RULE = {
    [key in OBJECTS]?: {
        [key in DIRECTIONS]?: DIRECTIONS
    }
}
export const change_direction_rules: DIRECTIONS_RULE = {
    [OBJECTS.LEFTDOWN]: {
        [DIRECTIONS.RIGHT]: DIRECTIONS.DOWN,
        [DIRECTIONS.UP]: DIRECTIONS.LEFT,
    },
    [OBJECTS.LEFTUP]: {
        [DIRECTIONS.RIGHT]: DIRECTIONS.UP,
        [DIRECTIONS.DOWN]: DIRECTIONS.LEFT,
    },
    [OBJECTS.RIGHTDOWN]: {
        [DIRECTIONS.LEFT]: DIRECTIONS.DOWN,
        [DIRECTIONS.UP]: DIRECTIONS.RIGHT,
    },
    [OBJECTS.RIGHTUP]: {
        [DIRECTIONS.LEFT]: DIRECTIONS.UP,
        [DIRECTIONS.DOWN]: DIRECTIONS.RIGHT,
    }
}

type SUMMAND = {
    [key in DIRECTIONS]: {
        x: number,
        y: number
    }
}
export const summand: SUMMAND = {
    [DIRECTIONS.DOWN]: {
        x: 1,
        y: 0
    },
    [DIRECTIONS.LEFT]: {
        x: 0,
        y: -1
    },
    [DIRECTIONS.RIGHT]: {
        x: 0,
        y: 1
    },
    [DIRECTIONS.UP]: {
        x: -1,
        y: 0
    },
}