export enum OBJECTS {
    NONE = 'NONE',
    VERTICAL = 'VERTICAL',
    HORIZONTAL = 'HORIZONTAL',
    LEFTDOWN = 'LEFTDOWN',
    LEFTUP = 'LEFTUP',
    RIGHTDOWN = 'RIGHTDOWN',
    RIGHTUP = 'RIGHTUP'
}

export enum DIRECTIONS {
    UP = 'UP',
    DOWN = 'DOWN',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT'
}

export type MAP = OBJECTS[][]

export const rules = {
    [OBJECTS.HORIZONTAL]: {
        [DIRECTIONS.RIGHT]: [OBJECTS.LEFTDOWN, OBJECTS.LEFTUP, OBJECTS.HORIZONTAL],
        [DIRECTIONS.LEFT]: [OBJECTS.RIGHTDOWN, OBJECTS.RIGHTUP, OBJECTS.HORIZONTAL]
    },
    [OBJECTS.VERTICAL]: {
        [DIRECTIONS.UP]: [OBJECTS.LEFTDOWN, OBJECTS.RIGHTDOWN, OBJECTS.VERTICAL],
        [DIRECTIONS.DOWN]: [OBJECTS.LEFTUP, OBJECTS.RIGHTUP, OBJECTS.VERTICAL]
    },
    [OBJECTS.LEFTDOWN]: {
        [DIRECTIONS.DOWN]: [OBJECTS.LEFTUP, OBJECTS.RIGHTUP, OBJECTS.VERTICAL],
        [DIRECTIONS.LEFT]: [OBJECTS.RIGHTUP, OBJECTS.RIGHTDOWN, OBJECTS.HORIZONTAL],
    },
    [OBJECTS.LEFTUP]: {
        [DIRECTIONS.UP]: [OBJECTS.RIGHTDOWN, OBJECTS.LEFTDOWN, OBJECTS.VERTICAL],
        [DIRECTIONS.LEFT]: [OBJECTS.RIGHTDOWN, OBJECTS.RIGHTUP, OBJECTS.HORIZONTAL],
    },
    [OBJECTS.RIGHTDOWN]: {
        [DIRECTIONS.DOWN]: [OBJECTS.LEFTUP, OBJECTS.RIGHTUP, OBJECTS.VERTICAL],
        [DIRECTIONS.RIGHT]: [OBJECTS.LEFTUP, OBJECTS.LEFTDOWN, OBJECTS.HORIZONTAL],
    },
    [OBJECTS.RIGHTUP]: {
        [DIRECTIONS.UP]: [OBJECTS.LEFTDOWN, OBJECTS.RIGHTDOWN, OBJECTS.VERTICAL],
        [DIRECTIONS.RIGHT]: [OBJECTS.LEFTDOWN, OBJECTS.LEFTUP, OBJECTS.HORIZONTAL],
    },
}